// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0iWYKU4fZisvccB6Bboad089BBufHUqg',
    appId: '1:271856290590:web:b398ff4f721f2f4ba8570f',
    messagingSenderId: '271856290590',
    projectId: 'estateagency-5e471',
    authDomain: 'estateagency-5e471.firebaseapp.com',
    storageBucket: 'estateagency-5e471.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABdRsntR5QSmyBoAkGp0uixcd8mdBGEt0',
    appId: '1:271856290590:android:835f268dc1916c7ca8570f',
    messagingSenderId: '271856290590',
    projectId: 'estateagency-5e471',
    storageBucket: 'estateagency-5e471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMEj8-_lR-lucSVPNzHN4LiE_lMsZIRQ',
    appId: '1:271856290590:ios:d91634ec665d0180a8570f',
    messagingSenderId: '271856290590',
    projectId: 'estateagency-5e471',
    storageBucket: 'estateagency-5e471.appspot.com',
    iosClientId: '271856290590-c195g7b4130r6l7olunh3uivk9upbmav.apps.googleusercontent.com',
    iosBundleId: 'com.example.experiance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMEj8-_lR-lucSVPNzHN4LiE_lMsZIRQ',
    appId: '1:271856290590:ios:4439f427c1516d3fa8570f',
    messagingSenderId: '271856290590',
    projectId: 'estateagency-5e471',
    storageBucket: 'estateagency-5e471.appspot.com',
    iosClientId: '271856290590-5nndtcrsc28hgnea23dg0uuulve0b2mm.apps.googleusercontent.com',
    iosBundleId: 'com.example.experiance.RunnerTests',
  );
}
